SELECT CART_ID
FROM CART_PRODUCTS AS a
JOIN (
    SELECT ID
    FROM CART_PRODUCTS
    GROUP BY CART_ID, NAME
    HAVING NAME IN ('MILK', 'YOGURT')
) AS b ON a.ID = b.ID
GROUP BY a.CART_ID
HAVING COUNT(*) = 2
ORDER BY CART_ID;