SELECT a.CAR_ID, a.CAR_TYPE, FLOOR((a.DAILY_FEE * 30 * (100 - c.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
    ON a.CAR_ID = b.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS c
    ON a.CAR_TYPE = c.CAR_TYPE
WHERE (a.CAR_TYPE = '세단' OR a.CAR_TYPE = 'SUV')
    AND a.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )   
    AND c.DURATION_TYPE = '30일 이상'
    AND (a.DAILY_FEE * 30 * (100 - c.DISCOUNT_RATE) / 100) >= 500000
    AND (a.DAILY_FEE * 30 * (100 - c.DISCOUNT_RATE) / 100) < 2000000
GROUP BY a.CAR_ID, FEE
ORDER BY a.CAR_ID;