SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM REST_INFO AS a
JOIN (
    SELECT 
        REST_ID, 
        RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKING
    FROM REST_INFO
) AS b ON a.REST_ID = b.REST_ID and b.RANKING = 1
ORDER BY a.FOOD_TYPE DESC;
        