SELECT
  ID,
  CASE
    WHEN cume <= 0.25 THEN 'CRITICAL'
    WHEN cume <= 0.5  THEN 'HIGH'
    WHEN cume <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS COLONY_NAME
FROM (
  SELECT
    ID,
    CUME_DIST() OVER (ORDER BY SIZE_OF_COLONY DESC) AS cume
  FROM ECOLI_DATA
) t
ORDER BY ID;