SELECT 
    b.USER_ID, 
    b.NICKNAME, 
    CONCAT_WS(' ', b.CITY, b.STREET_ADDRESS1, b.STREET_ADDRESS2) AS 전체주소,
    REGEXP_REPLACE(b.TLNO, '^([0-9]{3})([0-9]{4})([0-9]{4})$',
                      '$1-$2-$3') AS 전화번호
FROM USED_GOODS_BOARD AS a
JOIN USED_GOODS_USER AS b ON a.WRITER_ID = b.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY b.USER_ID DESC;
