SELECT
    YEAR(a.SALES_DATE) AS YEAR, 
    MONTH(a.SALES_DATE) AS MONTH, 
    b.GENDER,
    COUNT(DISTINCT a.USER_ID) AS USERS
FROM ONLINE_SALE AS a
JOIN USER_INFO AS b ON a.USER_ID = b.USER_ID
WHERE b.GENDER IS NOT NULL
GROUP BY YEAR(a.SALES_DATE), MONTH(a.SALES_DATE), b.GENDER
ORDER BY YEAR(a.SALES_DATE), MONTH(a.SALES_DATE), b.GENDER;