SELECT
    c.YEAR, 
    c.MONTH,
    COUNT(*) AS PURCHASED_USERS,
    ROUND(COUNT(*) /(SELECT COUNT(*) FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'),1) AS PUCHASED_RATIO
FROM (
    SELECT
        YEAR(a.SALES_DATE) AS YEAR, 
        MONTH(a.SALES_DATE) AS MONTH,
        b.USER_ID
    FROM ONLINE_SALE AS a
    JOIN USER_INFO AS b ON a.USER_ID = b.USER_ID
        AND b.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
    GROUP BY YEAR(a.SALES_DATE), MONTH(a.SALES_DATE), b.USER_ID
)AS c
GROUP BY c.YEAR, c.MONTH
ORDER BY c.YEAR, c.MONTH;