WITH RECURSIVE G AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        c.ID,
        c.PARENT_ID,
        p.GENERATION + 1
    FROM ECOLI_DATA AS c
    JOIN G AS p ON c.PARENT_ID = p.ID
)
SELECT 
    COUNT(*) AS COUNT,
    GENERATION
FROM G
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;