WITH R AS (
  SELECT
      h.HISTORY_ID,
      c.CAR_TYPE,
      c.DAILY_FEE,
      DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS RENTAL_DAYS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
  JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
  WHERE c.CAR_TYPE = '트럭'
)
SELECT
    R.HISTORY_ID,
    ROUND(R.DAILY_FEE * R.RENTAL_DAYS * (100 - IFNULL(p.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
  ON p.CAR_TYPE = R.CAR_TYPE
 AND (
        (p.DURATION_TYPE = '90일 이상' AND R.RENTAL_DAYS >= 90)
     OR (p.DURATION_TYPE = '30일 이상' AND R.RENTAL_DAYS >= 30 AND R.RENTAL_DAYS < 90)
     OR (p.DURATION_TYPE = '7일 이상'  AND R.RENTAL_DAYS >= 7  AND R.RENTAL_DAYS < 30)
    )
ORDER BY FEE DESC, R.HISTORY_ID DESC;