SELECT sub.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) AS sub
JOIN FIRST_HALF AS f
    ON f.FLAVOR = sub.FLAVOR
ORDER BY sub.TOTAL_ORDER + f.TOTAL_ORDER DESC
LIMIT 3;



