SELECT
    a.FLAVOR
FROM FIRST_HALF AS a 
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
) AS b ON a.FLAVOR = b.FLAVOR
GROUP BY a.FLAVOR
ORDER BY SUM(a.TOTAL_ORDER) + b.TOTAL DESC
LIMIT 3;