SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM SKILLCODES AS s
JOIN DEVELOPERS AS d
    ON (s.CODE & d.SKILL_CODE ) > 0
WHERE s.CATEGORY = 'Front End'
ORDER BY d.ID;

# SELECT NAME, CATEGORY
# FROM SKILLCODES
# WHERE CATEGORY = 'Front End';
