SELECT a.USER_ID, a.NICKNAME, SUM(b.price) AS TOTAL_SALES
From USED_GOODS_USER AS a
JOIN USED_GOODS_BOARD AS b ON a.USER_ID = b.WRITER_ID
WHERE b.STATUS = 'DONE'
GROUP BY a.USER_ID
HAVING SUM(b.price) >= 700000
ORDER BY TOTAL_SALES;

