SELECT
    c.MEMBER_NAME,
    a.REVIEW_TEXT,
    DATE_FORMAT(a.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS a
JOIN (
    SELECT
        MEMBER_ID,
        RANK() OVER(ORDER BY COUNT(*) DESC) AS RNK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) AS b ON b.RNK = 1 AND a.MEMBER_ID = b.MEMBER_ID
JOIN MEMBER_PROFILE AS c ON a.MEMBER_ID = c.MEMBER_ID
ORDER BY REVIEW_DATE, a.REVIEW_TEXT;
