WITH RANK_REVIEW AS (
    SELECT 
        MEMBER_ID, 
        COUNT(*) AS CNT,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT 
    a.MEMBER_NAME,
    b.REVIEW_TEXT,
    DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS a
JOIN REST_REVIEW AS b
    ON a.MEMBER_ID = b.MEMBER_ID
JOIN RANK_REVIEW AS c
    ON a.MEMBER_ID = c.MEMBER_ID
WHERE c.rnk = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT;