SELECT
    a.ITEM_ID,
    c.ITEM_NAME,
    c.RARITY
FROM ITEM_TREE AS a
JOIN ITEM_INFO AS b ON a.PARENT_ITEM_ID = b.ITEM_ID AND b.RARITY = 'RARE'
JOIN ITEM_INFO AS c ON a.ITEM_ID = c.ITEM_ID
ORDER BY a.ITEM_ID DESC;