-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO a
WHERE a.ITEM_ID IN (select ITEM_ID
from ITEM_TREE
Where PARENT_ITEM_ID IN (select ITEM_ID
from ITEM_INFO
where RARITY = 'RARE'))
ORDER BY ITEM_ID DESC;