SELECT DISTINCT a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
    ON a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE = '세단' AND SUBSTR(b.START_DATE,6,2) = '10'
ORDER BY a.CAR_ID DESC;