SELECT CONCAT('/home/grep/src/', C.BOARD_ID, '/', C.FILE_ID, C.FILE_NAME, C.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS A
LEFT JOIN (
    SELECT 
        BOARD_ID, 
        ROW_NUMBER() OVER (ORDER BY VIEWS DESC) AS RANKING
    FROM USED_GOODS_BOARD) AS B 
ON A.BOARD_ID = B.BOARD_ID
LEFT JOIN USED_GOODS_FILE AS C ON A.BOARD_ID = C.BOARD_ID
WHERE B.RANKING = 1
ORDER BY C.FILE_ID DESC;