-- 코드를 입력하세요
SELECT 
    a.CATEGORY, SUM(b.SALES) AS TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b on a.BOOK_ID = b.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY;