SELECT 
    CATEGORY, 
    PRICE, 
    PRODUCT_NAME
FROM (
    SELECT 
        CATEGORY, 
        PRICE, 
        PRODUCT_NAME,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING
    FROM FOOD_PRODUCT
) RANKED
WHERE RANKED.RANKING = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;