SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(a.LENGTH) AS MAX_LENGTH,
    a.FISH_TYPE
FROM (
    SELECT
        FISH_TYPE,
        IF (LENGTH IS NULL, 10, LENGTH) AS LENGTH
    FROM FISH_INFO
) AS a
GROUP BY a.FISH_TYPE
HAVING AVG(a.LENGTH) >= 33
ORDER BY a.FISH_TYPE;
